import * as t from "./theme.js";

// Version info comes from .env.production/.env.development, generated by
// generate-env.mjs just before the build runs (see package.json's "build"
// script) — VITE_APP_VERSION is the hand-bumped semver from package.json,
// VITE_BUILD_HASH/VITE_BUILD_DATE are captured automatically every build.
export default function AboutPage({ onClose }) {
  return (
    <div style={{ ...t.fullScreenOverlay, display: "flex", flexDirection: "column" }}>
      <div style={{ flex: 1, overflowY: "auto", padding: "16px" }}>
        <h1 style={{ marginTop: 0, marginBottom: 4 }}>Temperatura</h1>
        <p style={{ color: t.colors.textMuted, marginTop: 0 }}>time x temperature</p>

        <p>
          Temperatura manages recipe steps by time and temperature, reading from a custom
          Bluetooth thermometer. Start a step and it tracks elapsed time or time within a
          temperature band, and alerts you with alarms you configure per step.
        </p>

        <p style={{ fontSize: 13, color: t.colors.textMuted }}>
          All your recipes and running instances are stored only on this device. Use Backup
          and Restore, or Export and Import for individual recipes, from this menu to move
          data between devices or keep a safety copy.
        </p>

        <p style={{ fontSize: 12.5, color: t.colors.textMuted, marginTop: 24 }}>
          Made by Chris Hilder. MIT License.
        </p>
        <p style={{ fontSize: 11, color: t.colors.textMuted }}>
          v{import.meta.env.VITE_APP_VERSION} · build {import.meta.env.VITE_BUILD_HASH} · {import.meta.env.VITE_BUILD_DATE}
        </p>
      </div>
      <div style={{ padding: 16, borderTop: `1px solid ${t.colors.border}` }}>
        <button style={{ ...t.primaryButton, width: "100%" }} onClick={onClose}>Done</button>
      </div>
    </div>
  );
}
